### ISSUE TITLE
/green

### ISSUE THREAD

**Issue by Explosives** [TotalFreedom/TF-WorldEdit#11] opened 2015-05-09 00:57 UTC
Someone always comes on and tells players to do /green 9001

And then when someone does it the server crashes

Everyone can agree it needs to be blocked or limited

**Comment by JeromSar** [comment] 2015-05-09 09:12
Duplicate of TotalFreedom/TotalFreedomMod#594

**Closed by JeromSar** 2015-05-09 09:12 UTC
